# -*- coding: utf-8 -*-
"""AGRICULTURE EXCELLENCE :HARNESSING PRECISION TECHNOLOGY FOR CROP YEILD .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1amOj1adPlTItKOSyOtduua_J9BTlk3X_
"""

import os
import pickle
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.model_selection import RandomizedSearchCV
from sklearn.metrics import accuracy_score, confusion_matrix, ConfusionMatrixDisplay, classification_report
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import LinearSVC
from sklearn.ensemble import VotingClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.ensemble import AdaBoostClassifier
from xgboost import XGBClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import f1_score, classification_report
from sklearn.calibration import CalibratedClassifierCV
from sklearn.preprocessing import LabelEncoder
import lightgbm as lgb
!pip install xgboost
import warnings
warnings.filterwarnings("ignore") # This ignores all warnings

import shutil
import os
import kagglehub

csv_path = "/content/Crop_recommendation_shuffled (1).csv"

if not os.path.exists(csv_path):
    dataset_dir = kagglehub.dataset_download("atharvaingle/Crop-recommendation-shuffled-dataset")
    src_file = os.path.join(dataset_dir, "Crop-recommendation-shuffled.csv")
    shutil.copy(src_file, csv_path)
    print(" CSV copied to:", csv_path)
else:
    print(" CSV already exists at:", csv_path)

DATA_PATH = '/content/Crop_recommendation_shuffled (1).csv'

df = pd.read_csv(DATA_PATH)

df.head(5)

df.describe(include="all")

df['label'].value_counts()

df.info()

# Select only the numerical columns before calculating correlation.
numerical_df = df.select_dtypes(include=['number'])
correlation_mat = numerical_df.corr()
correlation_mat

plt.figure(figsize=(10,8))
sns.heatmap(correlation_mat, linewidths=.5,annot=True, fmt="f")

df.isnull().sum()
df = df.dropna()
sns.heatmap(df.isnull())
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns
plt.figure(figsize=(25,8))
df['label'] = df['label'].astype('category')
sns.countplot(x='label', data=df)
plt.title('Distribution of Feature')
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns
plt.figure(figsize=(25,8))
df['label'].hist()
plt.title('Distribution of Feature')
plt.show()

df.shape

X = df.iloc[:,:-1]     # selecting all features except 'label' feature
y = df.iloc[:,-1]      # selecting 'label' feature as dependent feature

# Splitting dataset into train and test data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state =2)

print('X_train shape:', X_train.shape)
print('X_test shape:', X_test.shape)
print('y_train shape:', y_train.shape)
print('y_test shape:', y_test.shape)

import joblib
# Create a dictionary to store models
models = {
    'LogisticRegression' : LogisticRegression(),
    'Probabilistic LogisticRegression' : CalibratedClassifierCV(LogisticRegression(),cv=5), # logistic regression with probabilistic interpretation
    'DecisionTree' : DecisionTreeClassifier(),
    'SVC': LinearSVC(random_state=1,C=0.05),
    'KNeighbors': KNeighborsClassifier(n_neighbors=5),
    'MultinomialNB': MultinomialNB(),
    'VotingClassifier' : VotingClassifier(estimators=[('LogisticRegression',LogisticRegression()),('DecisionTree',DecisionTreeClassifier()),('KNeighbors',KNeighborsClassifier(n_neighbors=5)),('MultinomialNB',MultinomialNB())],voting='soft'),
    'RandomForest': RandomForestClassifier(n_estimators=100, random_state=42),
    'AdaBoost' : AdaBoostClassifier(n_estimators=100),
    'GradientBoosting': GradientBoostingClassifier(n_estimators=100, random_state=42),
    'LightGBM' : lgb.LGBMClassifier(n_estimators=100, random_state=42, verbose=-1),
    'XGBoost' : XGBClassifier(n_estimators=100, random_state=42),
}

# Initialize LabelEncoder
label_encoder = LabelEncoder()
import warnings
warnings.filterwarnings('ignore')  # Suppress warnings (including LightGBM) before training


# Fit the encoder on the training labels and transform both training and testing labels
y_train_encoded = label_encoder.fit_transform(y_train)
y_test_encoded = label_encoder.transform(y_test)

# Loop through the models, train, test, and print results
for model_name, model in models.items():
    # Train the model
    model.fit(X_train, y_train_encoded)  # Use encoded labels for training

    # Test the model
    predictions = model.predict(X_test)

    # Decode predictions for evaluation
    decoded_predictions = label_encoder.inverse_transform(predictions)

    # Calculate accuracy
    f1 = f1_score(y_test, decoded_predictions, average='weighted')  # Use original labels for evaluation
    print(f"{model_name} F1 Score: {f1}")

    # Print classification report
    print(classification_report(y_test, decoded_predictions))  # Use original labels for evaluation

    # Calculate confusion matrix
    cm = confusion_matrix(y_test,decoded_predictions)

    # Plot confusion matrix
    plt.figure(figsize=(8, 6))
    sns.heatmap(cm, annot=True, cmap='Blues', fmt='g', cbar=False)
    plt.xlabel('Predicted')
    plt.ylabel('True')
    plt.title(f'{model_name} Confusion Matrix')
    plt.show()
    print("\n" + "="*40 + "\n")
    # Dump each model into separate files
    file_name = model_name.lower().replace(' ', '_') + '_model.pkl'
    with open(file_name, 'wb') as f:
        pickle.dump(model, f)
        print(f"{model_name} model saved as {file_name}")

def create_model(model):
    model.fit(X_train, y_train)
    Y_pred = model.predict(X_test)
    print("Classification Report")
    print(classification_report(y_test, Y_pred))
    cm = confusion_matrix(y_test, Y_pred)

    # Plot confusion matrix
    plt.figure(figsize=(8, 6))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')
    plt.xlabel('Predicted labels')
    plt.ylabel('True labels')
    plt.title('Confusion Matrix')
    plt.show()

    # Calculate and print accuracy score
    accuracy = accuracy_score(y_test, Y_pred)
    print("Accuracy Score:", accuracy)

    return model

from sklearn.ensemble import BaggingClassifier
# Bagging for LogisticRegression
bc=BaggingClassifier(LogisticRegression(),n_estimators=10,max_samples=1500,random_state=1)
bc=create_model(bc)

# Bagging for ProbabilisticLR
bc1=BaggingClassifier(CalibratedClassifierCV(LogisticRegression(),cv=5),n_estimators=10,max_samples=1500,random_state=1)
bc1=create_model(bc1)

#Bagging for DecisionTreeClassifier
bc2=BaggingClassifier(DecisionTreeClassifier(),n_estimators=10,max_samples=1500,random_state=1)
bc2=create_model(bc2)

#Bagging for LinearSVC
bc3=BaggingClassifier(LinearSVC(random_state=1,C=0.05),n_estimators=10,max_samples=1500,random_state=1)
bc3=create_model(bc3)

# Bagging for KNeighbors
bc4=BaggingClassifier(KNeighborsClassifier(n_neighbors=5),n_estimators=10,max_samples=1500,random_state=1)
bc4=create_model(bc4)

# Bagging for MultinomialNB
bc5=BaggingClassifier(MultinomialNB(),n_estimators=10,max_samples=1500,random_state=1)
bc5=create_model(bc5)

# Pasting for LogisticRegression
pc=BaggingClassifier(LogisticRegression(),n_estimators=10,max_samples=1500,random_state=1,bootstrap=False)
pc=create_model(pc)

# Pasting for ProbabilisticLR
pc1=BaggingClassifier(CalibratedClassifierCV(LogisticRegression(),cv=5),n_estimators=10,max_samples=1500,random_state=1,bootstrap=False)
pc1=create_model(pc1)

# Pasting for DecisionTreeClassifier
pc2=BaggingClassifier(DecisionTreeClassifier(),n_estimators=10,max_samples=1500,random_state=1,bootstrap=False)
pc2=create_model(pc2)

# Pasting for LinearSVC
pc3=BaggingClassifier(LinearSVC(random_state=1,C=0.05),n_estimators=10,max_samples=1500,random_state=1,bootstrap=False)
pc3=create_model(pc3)

# Pasting for KNeighbors
pc4=BaggingClassifier(KNeighborsClassifier(n_neighbors=5),n_estimators=10,max_samples=1500,random_state=1,bootstrap=False)
pc4=create_model(pc4)

# Pasting for MultinomialNB
pc5=BaggingClassifier(MultinomialNB(),n_estimators=10,max_samples=1500,random_state=1,bootstrap=False)
pc5=create_model(pc5)

from mlxtend.classifier import StackingClassifier
from sklearn.preprocessing import LabelEncoder
# Initialize LabelEncoder
label_encoder = LabelEncoder()

# Fit the encoder on the training labels and transform both training and testing labels
y_train_encoded = label_encoder.fit_transform(y_train)
y_test_encoded = label_encoder.transform(y_test)

LR=LogisticRegression()
ProbabilisticLR = CalibratedClassifierCV(LogisticRegression(),cv=5)
DT=DecisionTreeClassifier()
SVC = LinearSVC(random_state=1,C=0.05)
KNeighbors = KNeighborsClassifier(n_neighbors=5)
model_list=[LR,ProbabilisticLR,DT,SVC,KNeighbors]
for model in model_list:
    # Train the model
    model.fit(X_train, y_train_encoded)  # Use encoded labels for training

    # Test the model
    predictions = model.predict(X_test)

    # Decode predictions for evaluation
    decoded_predictions = label_encoder.inverse_transform(predictions)

    # Calculate accuracy
    f1 = f1_score(y_test, decoded_predictions, average='weighted')  # Use original labels for evaluation
    print(type(model).__name__+":",f1)

    # Print classification report
    print(classification_report(y_test, decoded_predictions))  # Use original labels for evaluation

    # Calculate confusion matrix
    cm = confusion_matrix(y_test,decoded_predictions)

    # Plot confusion matrix
    plt.figure(figsize=(8, 6))
    sns.heatmap(cm, annot=True, cmap='Blues', fmt='g', cbar=False)
    plt.xlabel('Predicted')
    plt.ylabel('True')
    plt.title(type(model).__name__+' Confusion Matrix')
    plt.show()

    print("\n" + "="*40 + "\n")
    # Save the fitted label encoder
import pickle

with open('label_encoder.pkl', 'wb') as f:
    pickle.dump(label_encoder, f)

print(" Label encoder saved as 'label_encoder.pkl'")

rice_df = df[df["label"] == 'rice']
jute_df = df[df["label"] == 'jute']
df_rice_jute = pd.concat([rice_df, jute_df])

# Function to change the width of bars in a plot
def change_width(ax, new_value):
    for patch in ax.patches:
        current_width = patch.get_width()
        diff = current_width - new_value
        # Change the bar width
        patch.set_width(new_value)
        # Recenter the bar
        patch.set_x(patch.get_x() + diff * .5)

# Define a consistent color palette
palette = sns.color_palette("husl", len(df['label'].unique()))

# Plot each column in the dataframe
for col in df.columns[:-1]:
    fig, ax = plt.subplots(1, 2, figsize=(15, 5), gridspec_kw={'width_ratios': [3.5, 0.5]})

    # Plot the main dataframe
    sns.barplot(x='label', y=col, data=df, ax=ax[0], palette=palette)
    ax[0].set_title(f'{col} Distribution')
    ax[0].set_ylabel(col)
    ax[0].set_xlabel('Label')
    ax[0].grid(True, which='both', linestyle='--', linewidth=0.5)

    # Plot the subset dataframe
    sns.barplot(x='label', y=col, data=df_rice_jute, ax=ax[1], palette=palette)
    change_width(ax[1], 0.5)
    ax[1].set_title(f'{col} Subset')
    ax[1].set_ylabel('')
    ax[1].set_xlabel('')
    ax[1].grid(True, which='both', linestyle='--', linewidth=0.5)

    # Set consistent y-axis limits
    max_val = max(df[col].max(), df_rice_jute[col].max())
    ax[0].set_ylim(0, max_val)
    ax[1].set_ylim(0, max_val)

    # Improve x-axis label formatting
    fig.autofmt_xdate(rotation=60)

    plt.tight_layout()
    plt.show()

import numpy as np
import pickle
from collections import Counter
from IPython.display import display
import requests
from PIL import Image as PILImage
from io import BytesIO

with open('label_encoder.pkl', 'rb') as le_file:
    label_encoder = pickle.load(le_file)

# Load pre-trained models
loaded_models = {}
model_files = {
    'LogisticRegression': 'logisticregression_model.pkl',
    'Probabilistic LogisticRegression': 'probabilistic_logisticregression_model.pkl',
    'DecisionTree': 'decisiontree_model.pkl',
    'SVC': 'svc_model.pkl',
    'KNeighbors': 'kneighbors_model.pkl',
    'MultinomialNB': 'multinomialnb_model.pkl',
    'VotingClassifier': 'votingclassifier_model.pkl',
    'RandomForest': 'randomforest_model.pkl',
    'AdaBoost': 'adaboost_model.pkl',
    'GradientBoosting': 'gradientboosting_model.pkl',
    'LightGBM': 'lightgbm_model.pkl',
    'XGBoost': 'xgboost_model.pkl',
}

for model_name, file_name in model_files.items():
    try:
        with open(file_name, 'rb') as f:
            model = pickle.load(f)
            loaded_models[model_name] = model
            print(f"Loaded {model_name} model successfully")
    except Exception as e:
        print(f"Error loading {model_name} model: {e}")

def predict_labels(sodium, potassium, phosphorus, temperature, humidity, ph, rainfall):
    user_input = np.array([[sodium, potassium, phosphorus, temperature, humidity, ph, rainfall]])

    predictions = []
    decoded_predictions = {}

    for model_name, model in loaded_models.items():
        try:
            encoded_label = model.predict(user_input)[0]
            decoded_label = label_encoder.inverse_transform([encoded_label])[0]
            predictions.append(decoded_label)
            decoded_predictions[model_name] = decoded_label
        except Exception as e:
            print(f"Error predicting labels using {model_name}: {e}")
            decoded_predictions[model_name] = "Error"

    # Majority voting
    final_crop = Counter(predictions).most_common(1)[0][0]
    print("\nFinal Recommended Crop:", final_crop)

    # Image mapping
    crop_images = {
        'apple': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSRDQPjtXnFzP3gjABS8wPsMwb8tLatM1t0ng&s',
        'banana': 'https://upload.wikimedia.org/wikipedia/commons/4/4c/Bananas.jpg',
        'blackgram': 'https://assets-news.housing.com/news/wp-content/uploads/2022/10/25151945/Black-gram-or-back-mung-bean.jpg',
        'chickpea': 'https://www.universaltradelink.net/images/productimg/11567753486.jpg',
        'coconut': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSXprvnQ_ZU8HWZQQMduaR49BuBrZc73XcE0A&s',
        'coffee': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS0a-3uyQ9B4bVyJmbPEeawulA4SLxp7f2cXA&s',
        'cotton': 'https://images.ctfassets.net/3s5io6mnxfqz/4TV7YTCO1DJuMhhn7RD1Ol/b5a6c12340e6529a86bc1b557ed2d8f8/AdobeStock_136921602.jpeg',
        'grapes': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSFFZRn0s7cAU2c_dBoK5iqapNcKqa4OwaC_g&s',
        'jute': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTmHLzZyTRddXjohuuwv2jLUyBJGELS_PkpNA&s',
        'kidneybeans': 'https://www.healthifyme.com/blog/wp-content/uploads/2022/01/807716893sst1641271427-scaled.jpg',
        'lentil': 'https://www.fieldstoneorganics.ca/wp-content/uploads/2023/05/Red-Lentils.jpg',
        'maize': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRfCuZvqpRYJv--ImVOFRbtOXjAIw-ItaYsYA&s',
        'mango': 'https://upload.wikimedia.org/wikipedia/commons/9/90/Hapus_Mango.jpg',
        'mothbeans': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR6dKkkhwLehX4LG2kxwo8C4p4LhMfGNBnMUA&s',
        'mungbean': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSdncW7dLhnBfXjcY3xWYBuujqfPVG4YmoPpg&s',
        'muskmelon': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSDVSqlPVcWW2CcDGFiVKlaEC1WOR1Sbhm0mA&s',
        'papaya': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRK0m58UoRZCFaiyJ4G9Bm0G0lDF__MH_NOww&s',
        'pigeonpeas': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRQBoUsFpW6bMZP_j6fZh-FEoJXCjU0oSzljFtiDlSG-rzA8Mvtso0pRhuAuvHPXA-I9cY&usqp=CAU',
        'pomegranate': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ9mG93vzJXNT-fUO2wi65Mf4VlSQZ1VTG99g&s',
        'rice': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQGY1YxhUGywhuwLeFswy8BHQimTC7nwECkUg&s',
        'watermelon': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRocXAegF4BhMZyP8hvIauJpYgHp71RYJ0lcA&s',
        'orange': 'https://upload.wikimedia.org/wikipedia/commons/c/c4/Orange-Fruit-Pieces.jpg'
    }

    if final_crop.lower() in crop_images:
        print("\nDisplaying image for", final_crop)
        try:
            headers = {'User-Agent': 'Mozilla/5.0'}
            response = requests.get(crop_images[final_crop.lower()], headers=headers)
            response.raise_for_status()
            img = PILImage.open(BytesIO(response.content)).convert("RGB")
            display(img)
        except Exception as e:
            print("Failed to load/display image:", e)
    return decoded_predictions

def validate_inputs(pH, temperature, humidity, rainfall):
    if pH < 3.5:
        return False, f"Invalid pH: {pH} — Too acidic. Crops cannot grow well in highly acidic soil."
    elif pH > 9.5:
        return False, f"Invalid pH: {pH} — Too alkaline. Most crops fail to absorb nutrients properly."

    if humidity < 0 or humidity > 100:
        return False, f"Invalid Humidity: {humidity}% — Humidity must be between 0% and 100%."

    if temperature < 0 or temperature > 60:
        return False, f"Invalid Temperature: {temperature}°C — Extreme temperatures are not suitable for crop growth."

    if rainfall < 0:
        return False, f"Invalid Rainfall: {rainfall}mm — Rainfall can't be negative."
    elif rainfall > 350:
        return False, f"Invalid Rainfall: {rainfall}mm — Too much rainfall may indicate flood conditions."

    return True, "Inputs are valid."


def main():
    print("Crop Recommendation System")
    print("Please enter the following parameters")

    try:
        sodium = float(input("Enter sodium level: "))
        potassium = float(input("Enter potassium level: "))
        phosphorus = float(input("Enter phosphorus level: "))
        temperature = float(input("Enter temperature: "))
        humidity = float(input("Enter humidity: "))
        ph = float(input("Enter pH level: "))
        rainfall = float(input("Enter rainfall: "))

        is_valid, message = validate_inputs(ph, temperature, humidity, rainfall)
        if not is_valid:
            print("\nError:", message)
            return

        predicted_labels = predict_labels(sodium, potassium, phosphorus, temperature, humidity, ph, rainfall)

        print("\nModel Predictions:")
        for model_name, label in predicted_labels.items():
            print(model_name, "predicted:", label)

    except ValueError:
        print("\nError: Please enter valid numerical values")

if __name__ == "__main__":
    main()